### ISSUE TITLE
Liga y vista de de la acreditación del inglés

### ISSUE THREAD

**Issue by gtzrvera** [gtzrvera/hypatia#2]
Crear liga y vista para los enlaces de la acreditación del inglés.
[Aqui esta la liga](http://hypatia.cucei.udg.mx/reforma/cursos/ingles/actividades.php)

**Comment by tickyrz** [comment]
00f0d3dc05ceba1dc33ab061cd3f62effd5f5a4d Se crea modelo, vista y template para apartado de acreditación de inglés
